### ISSUE TITLE
Error whilst evaluating fine-tuned model with categorical GO terms

### ISSUE THREAD

**Issue by mah51** [nadavbra/protein_bert#11]
Hello,

I am specifically looking to use the model to predict go terms on sequences less than 150 AAs in length so I am attempting to fine tune the model to my dataset of small sequences. The fine-tune process seems successful, however when I run the `evaluate_by_len` method in `finetuning.py` I get an out of memory error (see below). The error is originating on line 90 from `y_pred = model.predict(X, batch_size = batch_size)` I have reduced the batch_size right down to 2 in an attempt to prevent the error however I have had no success. I just wanted to check that I am inputting the data correctly and that it isn't a problem with my code. 

<details>
<summary>Code & inputs into methods</summary>

```
 save_data = {
      "benchmark_name": BENCHMARK_NAME,
      "samples": [('Training-set', (train_set_seqs, train_set_labels)), ('Validation-set', (valid_set_seqs, valid_set_labels))],
      "model_generator": model_generator,
      "input_encoder": input_encoder,
      "output_spec": output_spec,
      "start_seq_len" : settings['seq_len'],
      "start_batch_size": settings['batch_size']
    }

for dataset_name, dataset in saved_data["samples"]:
          log('*** %s performance: ***' % dataset_name)
          log('batch size: ', saved_data["start_batch_size"])
          results, confusion_matrix = evaluate_by_len(saved_data["model_generator"], saved_data["input_encoder"], saved_data["output_spec"], dataset[0], dataset[1], \
                  start_seq_len = saved_data["start_seq_len"], start_batch_size = saved_data["start_batch_size"])
```
(These are entered as dataframes which I assume is the correct input format, but just want to check.)
dataset[0]:
(dataframes.head() method)
```
Name: seq, dtype: object
P82299                               GAYGQGQNIGQLFVNILIFLFY
O46577    SVVKSEDFSLPAYMDRRDHPLPEVAHVKHLSASQKALKEKEKASWS...
A0QKT3    MPTYAPKAGDTTRSWYVIDATDVVLGRLAVAAANLLRGKHKPTFAP...
Q4QM28    MYAVFQSGGKQHRVSEGQVVRLEKLELATGATVEFDSVLMVVNGED...
A7GR09    MKWWKLSGQILLLFCFAWTGEWIAKQVHLPIPGSIIGIFLLLISLK...
```
dataset[1]:

```
P82299                             [GO:0005615, GO:0005344]
O46577    [GO:0016021, GO:0005743, GO:0005751, GO:000412...
A0QKT3                 [GO:0005840, GO:0003735, GO:0006412]
Q4QM28     [GO:0005840, GO:0019843, GO:0003735, GO:0006412]
A7GR09     [GO:0016021, GO:0005886, GO:0019835, GO:0012501]
```
</details>

<details>
<summary>OOM Error</summary>

```
2022-03-01 15:33:19.980713: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 1 with properties: 
pciBusID: 0000:84:00.0 name: Tesla P100-PCIE-12GB computeCapability: 6.0
coreClock: 1.3285GHz coreCount: 56 deviceMemorySize: 11.91GiB deviceMemoryBandwidth: 511.41GiB/s
2022-03-01 15:33:19.980756: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2022-03-01 15:33:19.980797: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2022-03-01 15:33:19.980817: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.11
2022-03-01 15:33:19.980840: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2022-03-01 15:33:19.980859: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2022-03-01 15:33:19.980881: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.10
2022-03-01 15:33:19.980904: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.11
2022-03-01 15:33:19.980948: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2022-03-01 15:33:19.981759: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0, 1
2022-03-01 15:33:19.981796: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2022-03-01 15:33:20.725621: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2022-03-01 15:33:20.725680: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      0 1 
2022-03-01 15:33:20.725691: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0:   N N 
2022-03-01 15:33:20.725697: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 1:   N N 
2022-03-01 15:33:20.726963: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 11119 MB memory) -> physical GPU (device: 0, name: Tesla P100-PCIE-12GB, pci bus id: 0000:08:00.0, compute capability: 6.0)
2022-03-01 15:33:20.728077: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 11119 MB memory) -> physical GPU (device: 1, name: Tesla P100-PCIE-12GB, pci bus id: 0000:84:00.0, compute capability: 6.0)
2022-03-01 15:33:22.452796: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2022-03-01 15:33:22.453398: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 3196210000 Hz
2022-03-01 15:33:23.836672: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2022-03-01 15:33:24.074444: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.11
2022-03-01 15:33:24.080029: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2022-03-01 15:33:24.943426: W tensorflow/stream_executor/gpu/asm_compiler.cc:63] Running ptxas --version returned 256
2022-03-01 15:33:24.995202: W tensorflow/stream_executor/gpu/redzone_allocator.cc:314] Internal: ptxas exited with non-zero error code 256, output: 
Relying on driver to perform ptx compilation. 
Modify $PATH to customize ptxas location.
This message will be only logged once.
2022-03-01 15:33:54.356200: W tensorflow/core/common_runtime/bfc_allocator.cc:433] Allocator (GPU_0_bfc) ran out of memory trying to allocate 128.0KiB (rounded to 131072)requested by op model_2/global-attention-block5/transpose_3
Current allocation summary follows.
2022-03-01 15:33:54.356891: I tensorflow/core/common_runtime/bfc_allocator.cc:972] BFCAllocator dump for GPU_0_bfc
2022-03-01 15:33:54.356918: I tensorflow/core/common_runtime/bfc_allocator.cc:979] Bin (256): 	Total Chunks: 31, Chunks in use: 31. 7.8KiB allocated for chunks. 7.8KiB in use in bin. 240B client-requested in use in bin.
2022-03-01 15:33:54.356930: I tensorflow/core/common_runtime/bfc_allocator.cc:979] Bin (512): 	Total Chunks: 50, Chunks in use: 50. 25.5KiB allocated for chunks. 25.5KiB in use in bin. 25.2KiB client-requested in use in bin.
2022-03-01 15:33:54.356939: I tensorflow/core/common_runtime/bfc_allocator.cc:979] Bin (1024): 	Total Chunks: 2, Chunks in use: 1. 2.8KiB allocated for chunks. 1.2KiB in use in bin. 1.0KiB client-requested in use in bin.
2022-03-01 15:33:54.356948: I tensorflow/core/common_runtime/bfc_allocator.cc:979] Bin (2048): 	Total Chunks: 38, Chunks in use: 38. 76.5KiB allocated for chunks. 76.5KiB in use in bin. 76.0KiB client-requested in use in bin.
2022-03-01 15:33:54.356956: I tensorflow/core/common_runtime/bfc_allocator.cc:979] Bin (4096): 	Total Chunks: 1, Chunks in use: 0. 5.2KiB allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2022-03-01 15:33:54.356965: I tensorflow/core/common_runtime/bfc_allocator.cc:979] Bin (8192): 	Total Chunks: 2, Chunks in use: 1. 26.0KiB allocated for chunks. 13.0KiB in use in bin. 13.0KiB client-requested in use in bin.
2022-03-01 15:33:54.356981: I tensorflow/core/common_runtime/bfc_allocator.cc:979] Bin (16384): 	Total Chunks: 3, Chunks in use: 1. 71.5KiB allocated for chunks. 20.5KiB in use in bin. 20.3KiB client-requested in use in bin.
2022-03-01 15:33:54.356990: I tensorflow/core/common_runtime/bfc_allocator.cc:979] Bin (32768): 	Total Chunks: 1, Chunks in use: 1. 51.0KiB allocated for chunks. 51.0KiB in use in bin. 34.9KiB client-requested in use in bin.
2022-03-01 15:33:54.356999: I tensorflow/core/common_runtime/bfc_allocator.cc:979] Bin (65536): 	Total Chunks: 8, Chunks in use: 8. 661.2KiB allocated for chunks. 661.2KiB in use in bin. 557.5KiB client-requested in use in bin.
2022-03-01 15:33:54.357008: I tensorflow/core/common_runtime/bfc_allocator.cc:979] Bin (131072): 	Total Chunks: 11, Chunks in use: 11. 1.50MiB allocated for chunks. 1.50MiB in use in bin. 1.32MiB client-requested in use in bin.
2022-03-01 15:33:54.357016: I tensorflow/core/common_runtime/bfc_allocator.cc:979] Bin (262144): 	Total Chunks: 17, Chunks in use: 17. 4.41MiB allocated for chunks. 4.41MiB in use in bin. 4.25MiB client-requested in use in bin.
..... (A lot more chunk messages)
memory_limit_: 11659697216 available bytes: 64 curr_region_allocation_bytes_: 23319394816
2022-03-01 15:34:14.429783: I tensorflow/core/common_runtime/bfc_allocator.cc:1048] Stats: 
Limit:                     11659697216
InUse:                     11659624704
MaxInUse:                  11659624704
NumAllocs:                     1112241
MaxAllocSize:                592642048
Reserved:                            0
PeakReserved:                        0
LargestFreeBlock:                    0
Traceback (most recent call last):
  File "/home/mah51/files/protein_bert/evaluate_go.py", line 37, in <module>
    run_job()
  File "/home/mah51/files/protein_bert/evaluate_go.py", line 27, in run_job
    start_seq_len = saved_data["start_seq_len"], start_batch_size = saved_data["start_batch_size"])
  File "/shared/home/mah51/files/protein_bert/proteinbert/finetuning.py", line 93, in evaluate_by_len
    y_pred = model.predict(X, batch_size = 1)
  File "/home/mah51/anaconda/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1629, in predict
    tmp_batch_outputs = self.predict_function(iterator)
  File "/home/mah51/anaconda/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "/home/mah51/anaconda/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 862, in _call
    results = self._stateful_fn(*args, **kwds)
  File "/home/mah51/anaconda/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2943, in __call__
    filtered_flat_args, captured_inputs=graph_function.captured_inputs)  # pylint: disable=protected-access
  File "/home/mah51/anaconda/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1919, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/mah51/anaconda/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 560, in call
    ctx=ctx)
  File "/home/mah51/anaconda/lib/python3.6/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.ResourceExhaustedError:  OOM when allocating tensor with shape[128,4,64] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[node model_2/global-attention-block5/transpose_3 (defined at shared/home/mah51/files/protein_bert/proteinbert/conv_and_global_attention_model.py:77) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
 [Op:__inference_predict_function_6175]

Function call stack:
predict_function
```

</details>

Thank you in advance for any help!

**Comment by mah51** [comment]
Thank you for the response @nadavbra.

Yes I provide the GO annotations as dataset[1], they aren't encoded. The OutputSpec is generated as follows:

`output_spec = OutputSpec(OutputType(True, 'categorical'), unique_labels)`.

I was unaware I had to encode the GO annotations as the model seems to train with them as a raw input and I assumed they were encoded as part of the `encode_dataset` method within `evaluate_by_len`.  Thanks.

**Comment by nadavbra** [comment]
The model was indeed pretrained to predict GO annotations, so it already outputs GO annotation predictions (however, as stated in [another issue](https://github.com/nadavbra/protein_bert/issues/6), there is a small problem with figuring out which output corresponds to which GO annotation). In your case, you may want to fine-tune the model anyway (or pretrain it from scratch), so it can predict the specific GO annotations that you care about (which might be different from the GO annotations we used during pretraining).

You can also pretrain a similar model from scratch with your specific sequences and GO annotations. We have instructions for how to pretrain a new ProteinBERT model.

Anyway, what you are trying to do won't work. You specify a sequential-categorical output, which is not the case for your data (there isn't a different output for each protein residue). You can think about your GO annotations as a set of independent binary predictions (one for each GO annotation).
There isn't a ready-to-use output type for that, meaning you will have to write some code if you want to fine-tune the existing ProteinBERT model. Basically, you will likely want to add a `Dense(k, activation = 'sigmoid')` layer on top of ProteinBERT's global output, where `k` is the number of GO annotations you want to predict.

Hope that helps.

**Comment by mah51** [comment]
Thank you very much for your assistance, I will give that a shot.
