### ISSUE TITLE
Error when trying to run benchmarks

### ISSUE THREAD

**Issue by sallyradwan** [nadavbra/protein_bert#75]
Hello, when trying to run the benchmarks from the jupyter notebook, which for various reasons I had to port to run in a local script instead, I received the following error message:

2023-12-23 18:19:26.336247: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2023-12-23 18:19:26.359764: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-12-23 18:19:26.359816: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-12-23 18:19:26.360542: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-12-23 18:19:26.364383: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2023-12-23 18:19:26.364542: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-12-23 18:19:28.150936: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
14945 training set records, 1661 validation set records, 4152 test set records.
Traceback (most recent call last):
File "/home/gradwan/protein_bert/sally1.py", line 37, in
pretrained_model_generator, input_encoder = load_pretrained_model()
File "/home/gradwan/protein_bert/proteinbert/existing_model_loading.py", line 54, in load_pretrained_model
return load_pretrained_model_from_dump(dump_file_path, create_model_function, create_model_kwargs = create_model_kwargs, optimizer_class = optimizer_class, lr = lr,
File "/home/gradwan/protein_bert/proteinbert/model_generation.py", line 159, in load_pretrained_model_from_dump
n_annotations, model_weights, optimizer_weights = pickle.load(f)
_pickle.UnpicklingError: invalid load key, 'v'.

I realize many of these are just warnings, but thought to include them in case they have any bearing on the error towards the end as I don't understand it at all.
If it makes a difference, I am trying to run this under WSL.
Any advice would be much appreciated. Thanks in advance!

**Comment by nadavbra** [comment]
Are you running the most updated version of ProteinBERT (from GitHub) with the recommended package versions? Did you manage to download the pickle file with the pretrained model? Maybe try deleting it and downloading it again manually.
