### ISSUE TITLE
Can I use this pre-trained model directly for analysis?

### ISSUE THREAD

**Issue by Yinlf1206** [nadavbra/protein_bert#97]
Hello,

Thank you for your work!

I have a data that contains a large number of very short amino acid sequences of length 6, as well as the number of times it appears in different species. I want to use the attention weight of the ProteinBERT model to calculate the significance of each amino acid sequence in this data, or in other words Capture the importance of each short amino acid sequence through the model.

Based on your experience, can I directly use this model for analysis? Do I need to use this data to train the ProteinBERT model again?

In addition, the program always reports that the shape of the data is inconsistent. How I convert these short amino acid sequences into the correct shape and input them into the model?

Thank you very much for your help!

The following is the error message of the program.

`30_species_ProtBERT_ver7.py:57: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  encoded_sequences = np.array([np.pad(seq, (0, max(0, seq_len - len(seq))), constant_values=0)[:seq_len]
Traceback (most recent call last):
  File "30_species_ProtBERT_ver7.py", line 101, in <module>
    compute_and_save_contributions(data_gen, intermediate_layer_model, kmers, output_file)
  File "30_species_ProtBERT_ver7.py", line 73, in compute_and_save_contributions
    for encoded_sequences, forms in data_gen:
  File "30_species_ProtBERT_ver7.py", line 57, in data_generator
    encoded_sequences = np.array([np.pad(seq, (0, max(0, seq_len - len(seq))), constant_values=0)[:seq_len]
ValueError: could not broadcast input array from shape (256,484) into shape (256)`

**Comment by FaisalAlj** [comment]
Hello team,

First off, I want to express my appreciation for the exceptional work on ProtBERT! It’s a powerful tool, and I am excited to incorporate it into my research.

I am currently integrating ProtBERT into my Conditional Variational Autoencoder (CVAE) project for regression and classification tasks. Specifically, I plan to use ProtBERT as a feature extractor to predict peptide inhibition concentrations and toxicity. These features will then feed into my CVAE model.

System Information
OS: Windows 11 (via WSL)
TensorFlow Version: 2.16
Keras Version: 3.0

Steps Taken and Issues Encountered
# 1. Installation and Initial Model Loading
I installed ProtBERT using Hugging Face's model hub.
I attempted to load the model using the following code:

```
#Path to the SavedModel directory
saved_model_path = "/home/fj/.cache/huggingface/hub/models--GrimSqueaker--proteinBERT/snapshots/3f75b5217a2232800d75f3e5d72b53c56bb97451"
#Load the model using load_model
model_layer = keras.models.load_model(saved_model_path)
```
Resulting Error:

```
ValueError: File format not supported...
```

The error indicates that Keras 3 only supports .keras and .h5 file formats, whereas the model is in a legacy SavedModel format.

# 2. Attempt with TFSMLayer
Following the suggested workaround in the error message, I loaded the model as a TFSMLayer:
```
# Load the model as a TFSMLayer
model_layer = keras.layers.TFSMLayer(saved_model_path, call_endpoint='serving_default')
model_layer._trainable = False
```
This successfully compiled.

# 3. Input Inspection

I inspected the expected input signatures using:

```
print(model_layer.call_endpoint_fn)
```

Output:

```
<ConcreteFunction (*, input_annotations: TensorSpec(shape=(None, 8943), dtype=tf.float32, name='input-annotations'), input_seq: TensorSpec(shape=(None, 1024), dtype=tf.int32, name='input-seq')) -> Dict...>
```

Additionally, I verified the model’s trainable variables using:


```
print(model_layer._trainable_variables)
```
# 4. Input Generation

To mimic the required input format, I attempted:

```
inputs = {
    'input_seq': tf.random.uniform((2, 1024), dtype=tf.int32, maxval=24),  # Must be int32
    'input_annotations': tf.random.uniform((2, 8943), dtype=tf.float32)  # Must be float32
}
outputs = model_layer.call(inputs=inputs)
```

Resulting Error:
```
TypeError: signature_wrapper(input-annotations, input-seq) takes 0 positional arguments, got 1
```

I also attempted passing inputs as separate arguments:

```
outputs = model_layer.call(input_seq=input_seq, input_annotations=input_annotations)
```
However, this approach also failed, as the model expects a single input argument.

# 5. Additional Observations

1-The call_endpoint_fn specifies the input signature as a dictionary of input_annotations and input_seq, but even after following this format, I am unable to pass data correctly.

2-I spent several days exploring potential fixes (varying input formats, inspecting trainable variables) without success.

Request for Guidance
Could you provide clarification on the following:

1-How to correctly format and pass the inputs (input_annotations and input_seq) to the TFSMLayer?
2-Any recommended debugging steps or specific requirements for working with TFSMLayer?
3-Is there a simplified example available for integrating ProtBERT with TensorFlow/Keras?

Thank you so much for your time and help!

**Comment by nadavbra** [comment]
Hi @Yinlf1206,

I'm not sure I understand what you're trying to do exactly. You should keep in mind that ProteinBERT was pretrained on amino-acid sequences that mostly describe full protein sequences, and not on 6-mers. However, it might still provide useful representations. I'd just try it empirically. 

Regarding your error, again, I'm not sure what you're trying to do exactly. Have you looked at the code samples we provide in our notebook? You may also want to search through past closed Issues here on this repo (I suspect many others have had similar issues).

**Comment by Yinlf1206** [comment]
Hi @nadavbra ,

I'm sorry that I don't describe my question clearly. 

In simple terms, I want to use the ProteinBERT model as a feature extractor to find distinctive sequences based on the input short sequence frequency data, and then I will use these sequences to perform regression and classification tasks through logistic regression model.

I know that the ProteinBERT model is not pre-trained for 6-mer, I just want to use it as a feature extractor, so I'm not sure if I should use this data to train the model further, perhaps I could just use the pre-trained model directly for feature extraction?

With regard to the problems encountered, I've solved them through checking past closed issues.

Below is a part of the input short sequence frequency file.

<img width="1236" alt="屏幕截图 2024-12-31 175647" src="https://github.com/user-attachments/assets/d3512c3b-af1d-4e25-8342-a5db2c5af5f2" />


Thank you very much for your help!

**Comment by nadavbra** [comment]
Are these 6-mers sliced from full protein sequences? If so I think it would make more sense to invoke ProteinBERT on the full protein sequences, and only then maybe slice the local embeddings to consider only 6 residues at a time.
But again, I can't provide solid advice without first understanding what you are trying to predict. It looks like you are trying to predict something per species, but I'm not sure what exactly.

**Comment by Yinlf1206** [comment]
OK, let me explain in detail what I have done so far and hopefully I can get your guidance and help.

All in all, I extracted k-mer sequences from the protein sequences of two types of plants and counted the number of times each k-mer appeared in each plant. By analyzing the k-mer frequency data, I hoped to find k-mer sequences that differed greatly between the two types of plants.

So, as you see, I have this data right now (The two types of plants are represented by 0 and 1 respectively in the 'form' column). Because there are so many sequences (maybe more than 300 million k-mer sequences totally), I want to to use the model to help me.

I see the ProtBERT model can extracting local and global features, maybe it will be help me to do this. I'm trying to use this model to predict sequences which differed greatly between the two types of plants.

Forgive me and correct me if I'm wrong about anything. Looking forward to your reply.

Thank you for your advice again!

**Comment by nadavbra** [comment]
@Yinlf1206 If you're just interested in finding kmers that differ between species, then it sounds like you don't really need ProteinBERT or any other AI - you can just count kmers and compare the counts. I think it only makes sense to use these tools if you're trying to predict something.

**Comment by Yinlf1206** [comment]
Thanks for your answer! I will re-evaluate how to continue this research.
